/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_E743B086__
#define __PLUGINEDITOR_H_E743B086__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class ConvolverAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    ConvolverAudioProcessorEditor (ConvolverAudioProcessor* ownerFilter);
    ~ConvolverAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_E743B086__
